//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferentionOrganisationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Result = new HashSet<Result>();
        }
    
        public int Event_Id { get; set; }
        public string Event_Name { get; set; }
        public Nullable<int> Event_Direction_Id { get; set; }
        public System.DateTime Event_Date { get; set; }
        public int Event_Duration_Days { get; set; }
        public int Event_City_Id { get; set; }
        public byte[] Event_Image { get; set; }
    
        public virtual City City { get; set; }
        public virtual Directions Directions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result { get; set; }
    }
}
