//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferentionOrganisationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Result = new HashSet<Result>();
            this.Result1 = new HashSet<Result>();
            this.Result2 = new HashSet<Result>();
            this.Result3 = new HashSet<Result>();
            this.Result4 = new HashSet<Result>();
            this.Result5 = new HashSet<Result>();
            this.Result6 = new HashSet<Result>();
        }
    
        public int User_Id { get; set; }
        public string User_Surname { get; set; }
        public string User_Name { get; set; }
        public string User_Patronym { get; set; }
        public string User_Email { get; set; }
        public Nullable<System.DateTime> User_Birthday { get; set; }
        public Nullable<int> User_Country_Id { get; set; }
        public string User_Phone { get; set; }
        public string User_Password { get; set; }
        public string User_Photo_Name { get; set; }
        public byte[] User_Photo { get; set; }
        public Nullable<int> User_Sex_Id { get; set; }
        public int User_Role_Id { get; set; }
        public Nullable<int> User_Direction_Id { get; set; }
        public Nullable<int> User_Event_Chain_Id { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Directions Directions { get; set; }
        public virtual Event_Chains Event_Chains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result6 { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Sexes Sexes { get; set; }
    }
}
